- name: import docker installation
  ansible.builtin.import_role:
    name: common

- name: start a container
  community.docker.docker_container:
    name: catalogue
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/user
    state: started
    restart: true
    ports:
      - "8080:8080"
    env:
      MONGO: "true"
      MONGO_URL: "mongodb://mongodb-dev.pdevops78.online:27017/users"
      REDIS_URL: "redis://redis-dev.pdevops78.online:6379"





