- name: import docker installation
  ansible.builtin.import_role:
    name: common

- name: start a container
  community.docker.docker_container:
    name: frontend
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
    state: started
    restart: true
    ports:
       - "8000:80"
    env:
      CATALOGUE_HOST: catalogue-dev.pdevops78.online
      CATALOGUE_PORT: 8080
      USER_HOST: user-dev.pdevops78.online
      USER_PORT: 8080
      CART_HOST: cart-dev.pdevops78.online
      CART_PORT: 8080
      SHIPPING_HOST: shipping-dev.pdevops78.online
      SHIPPING_PORT: 8080
      PAYMENT_HOST: payment-dev.pdevops78.online
      PAYMENT_PORT: 8080




