- name: import docker installation
  ansible.builtin.include_role:
    name: common

- name: start a container
  community.docker.docker_container:
    name: catalogue
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
    state: started
    restart: true
    ports:
      - "8080:8080"
    env:
      MONGO: "true"
      MONGO_URL: "mongodb://mongodb-dev.pdevops78.online:27017/catalogue"


- name: Load schema
  community.docker.docker_container:
    name: schema-load
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    restart: true
    env:
      DB_TYPE:   "mongo"
      APP_GIT_URL: "https://github.com/roboshop-devops-project-v3/catalogue"
      DB_HOST:  "mongodb-dev.pdevops78.online"
      SCHEMA_FILE: "db/master-data.js"





# docker run -e DB_TYPE=mongo -e APP_GIT_URL=https://github.com/roboshop-devops-project-v3/catalogue -e DB_HOST=mongo-ip -e SCHEMA_FILE=db/master-data.js public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load









