- name: Download component
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: docker-ce.repo

- name: install docker
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core
      - docker-ce
    state: installed

- name: start  service
  ansible.builtin.systemd_service:
    name: docker
    state: restarted
    enabled: true
