- name: import docker installation
  ansible.builtin.import_role:
    name: common

- name: start a container
  community.docker.docker_container:
    name: catalogue
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/cart
    state: started
    restart: true
    ports:
      - "8000:8080"
    env:
      CATALOGUE_HOST: catalogue-dev.pdevops78.online
      CATALOGUE_PORT: 8080
      REDIS_HOST: redis-dev.pdevops78.online

